#!/bin/bash 

function genelSorgu() {
  toplam = $(dpkg -l | wc -l)
  echo $toplam
}

function paketSorgu() {
  paket = $1
  yuklumu = $(dpkg -s $paket)
  paketdepencount = $(apt-cache depends $paket | wc -l)

  if[ !yuklumu ]
  then
    echo "$paket yuklu degil, bagimlilik sayisi $paketdepencount" 
  else
    echo "$paket yuklu"
  fi
}
---
aldığım hata -> ![1](https://user-images.githubusercontent.com/37108233/132761081-94286b67-081f-42fa-a166-d9c4c2e31067.PNG)
---
